### PR TITLE
fix(kong): upgrade --install and handle error properly

### LINKED ISSUE #533: GKE addon: spawning cluster sometimes succeeds but ktf reports a failure
Is seems that sometimes cluster creation can succeed but ktf will report a failure and leave the clsuter behind.

Example: https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371

```
=== RUN   TestGKECluster/create_subnet_(using_gcloud_CLI)
    gke_cluster_test.go:52: configuring GKE cloud environment for tests
    gke_cluster_test.go:57: verifying integrity of the gcloud credentials
    gke_cluster_test.go:64: configuring the GKE cluster PROJECT=(***) LOCATION=(***)
    gke_cluster_test.go:70: building cluster t-c1c7f401-828c-4352-9e81-35c8832a0990 (this can take some time)
    gke_cluster_test.go:74: setting up cleanup for cluster t-c1c7f401-828c-4352-9e81-35c8832a0990
    gke_cluster_test.go:80: verifying that the cluster can be communicated with
    gke_cluster_test.go:83: server version found: v1.23.15-gke.1900
    gke_cluster_test.go:85: verifying that the cluster can be loaded as an existing cluster
    gke_cluster_test.go:89: verifying cluster is labelled properly in GKE
    gke_cluster_test.go:97: verify createdBy label exists
    gke_cluster_test.go:107: loading the gke cluster into a testing environment and deploying kong addon
time="2023-02-03T12:54:26Z" level=error msg="failed running helm" args="[--kubeconfig /tmp/-kubeconfig-t-c1c7f401-828c-4352-9e81-35c8832a0990[13](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:14)26361968 install ingress-controller kong/kong --namespace kong-system --set admin.type=ClusterIP --set proxy.type=LoadBalancer --set proxy.http.nodePort=30080 --set admin.enabled=true --set admin.http.enabled=true --set admin.http.nodePort=32080 --set admin.tls.enabled=false --set tls.enabled=false --set udpProxy.enabled=true --set proxy.stream[0].containerPort=8888 --set proxy.stream[0].servicePort=8888 --set proxy.stream[1].containerPort=8899 --set proxy.stream[1].servicePort=8899 --set proxy.stream[1].parameters[0]=ssl --set proxy.stream[1].parameters[1]=reuseport --set udpProxy.stream[0].containerPort=9999 --set udpProxy.stream[0].servicePort=9999 --set udpProxy.stream[0].protocol=UDP --set udpProxy.stream[0].parameters[0]=udp --set udpProxy.stream[0].parameters[1]=reuseport]" error="E0203 12:54:13.086423   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:13.218093   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:13.420917   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:13.543544   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:13.739748   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:13.821099   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:[14](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:15).034596   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.112232   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.311835   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.388024   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.628632   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.71[15](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:16)47   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.912154   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:14.997618   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:[16](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:17).355604   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:16.628245   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:16.710978   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:19.559637   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:19.646767   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:19.857710   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:19.919748   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.1[17](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:18)680   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.193511   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.387122   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.472169   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.665099   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.748891   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:20.940234   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.019257   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.214359   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.293763   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.492126   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.576451   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.771383   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:21.847390   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:22.172339   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:22.244005   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:22.441703   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:22.516517   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:22.715620   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:22.7933[18](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:19)   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0[20](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:21)3 12:54:[22](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:23).989843   10351 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:[23](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:24).075773   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:23.265520   10351 memcache.go:[25](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:26)5] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\nE0203 12:54:23.346894   10351 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request\n: %!w(<nil>)"
    gke_cluster_test.go:111: waiting for addons to be ready
    gke_cluster_test.go:112: 
        	Error Trace:	/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/gke_cluster_test.go:112
        	            				/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/gke_cluster_test.go:40
        	Error:      	Received unexpected error:
        	            	Get "https://35.2[26](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:27).89.162/apis/apps/v1/namespaces/kong-system/daemonsets": context deadline exceeded
        	Test:       	TestGKECluster/create_subnet_(using_gcloud_CLI)
    gke_cluster_test.go:76: running cluster cleanup for t-c1c7f401-8[28](https://github.com/Kong/kubernetes-testing-framework/actions/runs/4084278728/jobs/7040792371#step:6:29)c-4352-9e81-35c8832a0990
    gke_cluster_test.go:77: 
        	Error Trace:	/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/gke_cluster_test.go:77
        	            				/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/panic.go:540
        	            				/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/testing.go:871
        	            				/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/gke_cluster_test.go:112
        	            				/home/runner/work/kubernetes-testing-framework/kubernetes-testing-framework/test/e2e/gke_cluster_test.go:40
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestGKECluster/create_subnet_(using_gcloud_CLI)
```

### Special notes for reviewers

Those GKE clusters have been removed manually

### PR DESCRIPTION
**Pull request by czeslavo**
I believe this should fix #533 root cause.

https://github.com/Kong/kubernetes-testing-framework/pull/523/files introduced `DoWithErrorHandling` which changed behavior of the helm install step of Kong addon. 

Before:
```
if err := cmd.Run(); err != nil {
		if !strings.Contains(stderr.String(), "cannot re-use") { // ignore if addon is already deployed
			return fmt.Errorf("%s: %w", stderr.String(), err)
		}
	}
```
 
After: 
```
return retry.
		Command("helm", args...).
		DoWithErrorHandling(ctx, func(err error, _, stderr *bytes.Buffer) error {
			if !strings.Contains(stderr.String(), "cannot re-use") {
				return fmt.Errorf("%s: %w", stderr, err)
			}
			return nil
		})
```

In the `after` version because of `DoWithErrorHandling` implementation calling the error handling function always, despite the error value, we were ending up retrying many times even if an error was nil.

### CODE REVIEW

File: internal/retry/command.go [hunk 1]
```diff
@@ -54,7 +54,10 @@ func (c commandDoer) DoWithErrorHandling(ctx context.Context, errorFunc ErrorFun
 	return retry.Do(func() error {
 		cmd, stdout, stderr := c.createCmd(ctx)
 		err := cmd.Run()
-		return errorFunc(err, stdout, stderr)
+		if err != nil {
+			return errorFunc(err, stdout, stderr)
+		}
+		return nil
```
Comment (pmalek) [inline internal/retry/command.go:60]: I'd leave this as is, always passing `err`, not only when it's `nil`.

Comment (czeslavo) [reply internal/retry/command.go:60]: IMO `DoWithErrorHandling` name suggests that the `ErrorFunc` it gets will be called when an error appears, not when it's nil. If it was to handle every result, it should be named differently, e.g. `DoWithResultHandling`.

Comment (pmalek) [reply internal/retry/command.go:60]: 🤔 Maybe you're right. I omitted that somehow. We might add a comment to `DoWithErrorHandling` that `err` is never `nil`.

Comment (czeslavo) [reply internal/retry/command.go:62]: PTAL: 1eb4a7c

**Review by pmalek — APPROVED** [review]
🏅 

Thanks for fixing this! And for adding tests!

**Comment by czeslavo** [comment]
Hm, it got merged despite the failing test :/

**Comment by czeslavo** [comment]
@pmalek https://github.com/Kong/kubernetes-testing-framework/pull/539/files
